---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Check for dhparam.pem
  stat: path=/etc/nginx/dhparam.pem
  register: dhparam

- name: Generate dhparam
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  when: dhparam.stat.exists == false

- name: Copy nginx default configuration
  template: src=nginx.conf dest=/etc/nginx/ owner=root group=root

- name: Copy default passenger configuration
  template: src=passenger.conf dest=/etc/nginx/conf.d owner=root group=root

- name: Disable default config
  file: path=/etc/nginx/sites-enabled/default state=absent
