---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Check for dhparam.pem
  stat: path=/etc/nginx/dhparam.pem
  register: dhparam

- name: Generate dhparam
  command: openssl dhparam -out /etc/nginx/dhparam.pem 4096
  when: nginx_https_enabled is defined and nginx_https_enabled == true and dhparam.stat.exists == false

- name: Copy nginx configuration (with HTTPS enabled)
  template: src=nginx_app_config_https dest=/etc/nginx/sites-available/{{ deploy_app_name }} owner=root group=root
  when: nginx_https_enabled is defined and nginx_https_enabled == true

- name: Copy nginx configuration (without HTTPS enabled)
  template: src=nginx_app_config dest=/etc/nginx/sites-available/{{ deploy_app_name }} owner=root group=root
  when: nginx_https_enabled is defined and nginx_https_enabled != true

- name: Disable default config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Symlink to sites-enabled
  file: src=/etc/nginx/sites-available/{{ deploy_app_name }} dest=/etc/nginx/sites-enabled/{{ deploy_app_name }} owner=root group=root state=link

- name: Copy htpasswd
  template: src=htpasswd dest=/etc/nginx/.htpasswd owner=root group=root
