- name: Installs ruby building dependencies
  become: yes
  become_method: sudo
  apt: name={{ item }} state=installed update-cache=yes
  with_items: "{{ ruby_deps }}"
  tags:
    - ruby
    - ruby:install
    - install


